'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ConsultaOrdemServico

    '''<summary>
    '''pnlPesquisa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPesquisa As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblTitPesquisar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitPesquisar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''drpTipoPequisa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpTipoPequisa As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''spanParametros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spanParametros As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtParametroPesquisa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtParametroPesquisa As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEmissao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmissao As Global.OrdemServico.DateBox

    '''<summary>
    '''txtCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCliente As Global.OrdemServico.ClienteView

    '''<summary>
    '''btnBuscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscar As Global.OrdemServico.AutoHideButton

    '''<summary>
    '''pnlIncluir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlIncluir As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnIncluir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnIncluir As Global.OrdemServico.AutoHideButton

    '''<summary>
    '''pnlResultado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlResultado As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlItens control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlItens As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''grdItens control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdItens As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''oMensagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents oMensagem As Global.OrdemServico.Mensagem
End Class
