'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
'
Namespace wsmicrosiga.ordemservico
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WSORDEMSERVICOSOAP", [Namespace]:="http://10.230.2.44:91/")>  _
    Partial Public Class WSORDEMSERVICO
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ALTERAROperationCompleted As System.Threading.SendOrPostCallback
        
        Private ATENDEROperationCompleted As System.Threading.SendOrPostCallback
        
        Private INCLUIROperationCompleted As System.Threading.SendOrPostCallback
        
        Private INCLUIROSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.OrdemServico.My.MySettings.Default.OrdemServico_wsmicrosiga_ordemservico_WSORDEMSERVICO
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ALTERARCompleted As ALTERARCompletedEventHandler
        
        '''<remarks/>
        Public Event ATENDERCompleted As ATENDERCompletedEventHandler
        
        '''<remarks/>
        Public Event INCLUIRCompleted As INCLUIRCompletedEventHandler
        
        '''<remarks/>
        Public Event INCLUIROSCompleted As INCLUIROSCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.230.2.44:91/ALTERAR", RequestNamespace:="http://10.230.2.44:91/", ResponseElementName:="ALTERARRESPONSE", ResponseNamespace:="http://10.230.2.44:91/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ALTERAR(ByVal TOKEN As TKNSTRUCT, ByVal FICHAORDEMSERVICO As FICHAORDEMSERVICOSTRUCT) As <System.Xml.Serialization.XmlElementAttribute("ALTERARRESULT")> RETSTRUCT
            Dim results() As Object = Me.Invoke("ALTERAR", New Object() {TOKEN, FICHAORDEMSERVICO})
            Return CType(results(0),RETSTRUCT)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ALTERARAsync(ByVal TOKEN As TKNSTRUCT, ByVal FICHAORDEMSERVICO As FICHAORDEMSERVICOSTRUCT)
            Me.ALTERARAsync(TOKEN, FICHAORDEMSERVICO, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ALTERARAsync(ByVal TOKEN As TKNSTRUCT, ByVal FICHAORDEMSERVICO As FICHAORDEMSERVICOSTRUCT, ByVal userState As Object)
            If (Me.ALTERAROperationCompleted Is Nothing) Then
                Me.ALTERAROperationCompleted = AddressOf Me.OnALTERAROperationCompleted
            End If
            Me.InvokeAsync("ALTERAR", New Object() {TOKEN, FICHAORDEMSERVICO}, Me.ALTERAROperationCompleted, userState)
        End Sub
        
        Private Sub OnALTERAROperationCompleted(ByVal arg As Object)
            If (Not (Me.ALTERARCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ALTERARCompleted(Me, New ALTERARCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.230.2.44:91/ATENDER", RequestNamespace:="http://10.230.2.44:91/", ResponseElementName:="ATENDERRESPONSE", ResponseNamespace:="http://10.230.2.44:91/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ATENDER(ByVal TOKEN As TKNSTRUCT, ByVal FICHAATENDIMENTO As FICHAATENDIMENTOSTRUCT) As <System.Xml.Serialization.XmlElementAttribute("ATENDERRESULT")> RETSTRUCT
            Dim results() As Object = Me.Invoke("ATENDER", New Object() {TOKEN, FICHAATENDIMENTO})
            Return CType(results(0),RETSTRUCT)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ATENDERAsync(ByVal TOKEN As TKNSTRUCT, ByVal FICHAATENDIMENTO As FICHAATENDIMENTOSTRUCT)
            Me.ATENDERAsync(TOKEN, FICHAATENDIMENTO, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ATENDERAsync(ByVal TOKEN As TKNSTRUCT, ByVal FICHAATENDIMENTO As FICHAATENDIMENTOSTRUCT, ByVal userState As Object)
            If (Me.ATENDEROperationCompleted Is Nothing) Then
                Me.ATENDEROperationCompleted = AddressOf Me.OnATENDEROperationCompleted
            End If
            Me.InvokeAsync("ATENDER", New Object() {TOKEN, FICHAATENDIMENTO}, Me.ATENDEROperationCompleted, userState)
        End Sub
        
        Private Sub OnATENDEROperationCompleted(ByVal arg As Object)
            If (Not (Me.ATENDERCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ATENDERCompleted(Me, New ATENDERCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.230.2.44:91/INCLUIR", RequestNamespace:="http://10.230.2.44:91/", ResponseElementName:="INCLUIRRESPONSE", ResponseNamespace:="http://10.230.2.44:91/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function INCLUIR(ByVal TOKEN As TKNSTRUCT, ByVal FICHAORDEMSERVICO As FICHAORDEMSERVICOSTRUCT) As <System.Xml.Serialization.XmlElementAttribute("INCLUIRRESULT")> RETSTRUCT
            Dim results() As Object = Me.Invoke("INCLUIR", New Object() {TOKEN, FICHAORDEMSERVICO})
            Return CType(results(0),RETSTRUCT)
        End Function
        
        '''<remarks/>
        Public Overloads Sub INCLUIRAsync(ByVal TOKEN As TKNSTRUCT, ByVal FICHAORDEMSERVICO As FICHAORDEMSERVICOSTRUCT)
            Me.INCLUIRAsync(TOKEN, FICHAORDEMSERVICO, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub INCLUIRAsync(ByVal TOKEN As TKNSTRUCT, ByVal FICHAORDEMSERVICO As FICHAORDEMSERVICOSTRUCT, ByVal userState As Object)
            If (Me.INCLUIROperationCompleted Is Nothing) Then
                Me.INCLUIROperationCompleted = AddressOf Me.OnINCLUIROperationCompleted
            End If
            Me.InvokeAsync("INCLUIR", New Object() {TOKEN, FICHAORDEMSERVICO}, Me.INCLUIROperationCompleted, userState)
        End Sub
        
        Private Sub OnINCLUIROperationCompleted(ByVal arg As Object)
            If (Not (Me.INCLUIRCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent INCLUIRCompleted(Me, New INCLUIRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.230.2.44:91/INCLUIROS", RequestNamespace:="http://10.230.2.44:91/", ResponseElementName:="INCLUIROSRESPONSE", ResponseNamespace:="http://10.230.2.44:91/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function INCLUIROS(ByVal TOKEN As TKNSTRUCT, ByVal FICHAORDEMSERVICO As FICHAORDEMSERVICOSTRUCT) As <System.Xml.Serialization.XmlElementAttribute("INCLUIROSRESULT")> RETSTRUCT
            Dim results() As Object = Me.Invoke("INCLUIROS", New Object() {TOKEN, FICHAORDEMSERVICO})
            Return CType(results(0),RETSTRUCT)
        End Function
        
        '''<remarks/>
        Public Overloads Sub INCLUIROSAsync(ByVal TOKEN As TKNSTRUCT, ByVal FICHAORDEMSERVICO As FICHAORDEMSERVICOSTRUCT)
            Me.INCLUIROSAsync(TOKEN, FICHAORDEMSERVICO, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub INCLUIROSAsync(ByVal TOKEN As TKNSTRUCT, ByVal FICHAORDEMSERVICO As FICHAORDEMSERVICOSTRUCT, ByVal userState As Object)
            If (Me.INCLUIROSOperationCompleted Is Nothing) Then
                Me.INCLUIROSOperationCompleted = AddressOf Me.OnINCLUIROSOperationCompleted
            End If
            Me.InvokeAsync("INCLUIROS", New Object() {TOKEN, FICHAORDEMSERVICO}, Me.INCLUIROSOperationCompleted, userState)
        End Sub
        
        Private Sub OnINCLUIROSOperationCompleted(ByVal arg As Object)
            If (Not (Me.INCLUIROSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent INCLUIROSCompleted(Me, New INCLUIROSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://10.230.2.44:91/")>  _
    Partial Public Class TKNSTRUCT
        
        Private cONTEUDOField As String
        
        Private eMPRESAFILIALField As EMPFILIALSTRUCT
        
        Private mENSAGEMField As String
        
        Private mODULOField As String
        
        Private sENHAField As String
        
        Private sESSIONIDField As String
        
        Private sISTEMAField As String
        
        '''<remarks/>
        Public Property CONTEUDO() As String
            Get
                Return Me.cONTEUDOField
            End Get
            Set
                Me.cONTEUDOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EMPRESAFILIAL() As EMPFILIALSTRUCT
            Get
                Return Me.eMPRESAFILIALField
            End Get
            Set
                Me.eMPRESAFILIALField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MENSAGEM() As String
            Get
                Return Me.mENSAGEMField
            End Get
            Set
                Me.mENSAGEMField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MODULO() As String
            Get
                Return Me.mODULOField
            End Get
            Set
                Me.mODULOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SENHA() As String
            Get
                Return Me.sENHAField
            End Get
            Set
                Me.sENHAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SESSIONID() As String
            Get
                Return Me.sESSIONIDField
            End Get
            Set
                Me.sESSIONIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SISTEMA() As String
            Get
                Return Me.sISTEMAField
            End Get
            Set
                Me.sISTEMAField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://10.230.2.44:91/")>  _
    Partial Public Class EMPFILIALSTRUCT
        
        Private eMPRESAField As String
        
        Private fILIALField As String
        
        Private fILPARField As String
        
        '''<remarks/>
        Public Property EMPRESA() As String
            Get
                Return Me.eMPRESAField
            End Get
            Set
                Me.eMPRESAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FILIAL() As String
            Get
                Return Me.fILIALField
            End Get
            Set
                Me.fILIALField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FILPAR() As String
            Get
                Return Me.fILPARField
            End Get
            Set
                Me.fILPARField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://10.230.2.44:91/")>  _
    Partial Public Class ITEMATENDIMENTOSTRUCT
        
        Private cODIGOPRODUTONOVOField As String
        
        Private d_E_L_E_T_Field As String
        
        Private nUMEROITEMField As String
        
        Private nUMEROLOTEField As String
        
        Private nUMEROSERIENOVOField As String
        
        Private nUMEROSERIEPECASField As String
        
        Private qUANTIDADEField As Single
        
        '''<remarks/>
        Public Property CODIGOPRODUTONOVO() As String
            Get
                Return Me.cODIGOPRODUTONOVOField
            End Get
            Set
                Me.cODIGOPRODUTONOVOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property D_E_L_E_T_() As String
            Get
                Return Me.d_E_L_E_T_Field
            End Get
            Set
                Me.d_E_L_E_T_Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NUMEROITEM() As String
            Get
                Return Me.nUMEROITEMField
            End Get
            Set
                Me.nUMEROITEMField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NUMEROLOTE() As String
            Get
                Return Me.nUMEROLOTEField
            End Get
            Set
                Me.nUMEROLOTEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NUMEROSERIENOVO() As String
            Get
                Return Me.nUMEROSERIENOVOField
            End Get
            Set
                Me.nUMEROSERIENOVOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NUMEROSERIEPECAS() As String
            Get
                Return Me.nUMEROSERIEPECASField
            End Get
            Set
                Me.nUMEROSERIEPECASField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property QUANTIDADE() As Single
            Get
                Return Me.qUANTIDADEField
            End Get
            Set
                Me.qUANTIDADEField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://10.230.2.44:91/")>  _
    Partial Public Class FICHAATENDIMENTOSTRUCT
        
        Private aPROVADO2ATENDIMENTOField As String
        
        Private aPROVADOATENDIMENTOField As String
        
        Private bLOQUEIOATENDIMENTOField As String
        
        Private cAUSAPROVAVELField As String
        
        Private cODIGODEFEITOField As String
        
        Private cODIGOGARANTIAField As String
        
        Private cODIGOOCORRENCIAField As String
        
        Private cODIGOSERVICOField As String
        
        Private cODIGOSITUACAOField As String
        
        Private cODIGOTECNICOField As String
        
        Private dATAFIMField As Date
        
        Private dATAINICIOField As Date
        
        Private dEFEITOCONSTATADOField As String
        
        Private hORAFIMField As String
        
        Private hORAINICIOField As String
        
        Private iNCLUIITEMOSField As String
        
        Private iTENSField() As ITEMATENDIMENTOSTRUCT
        
        Private mODOATENDIMENTOField As String
        
        Private nUMEROATENDIMENTOOSField As String
        
        Private nUMEROSERIEEQUIPField As String
        
        Private oRDEMSERVICOField As String
        
        Private sEQUENCIAATENDIMENTOOSField As String
        
        Private sERVICOEXECUTADOField As String
        
        Private tRASLADOField As String
        
        Private vERSAOATUALField As String
        
        Private vERSAOSOFTWAREField As String
        
        '''<remarks/>
        Public Property APROVADO2ATENDIMENTO() As String
            Get
                Return Me.aPROVADO2ATENDIMENTOField
            End Get
            Set
                Me.aPROVADO2ATENDIMENTOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property APROVADOATENDIMENTO() As String
            Get
                Return Me.aPROVADOATENDIMENTOField
            End Get
            Set
                Me.aPROVADOATENDIMENTOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BLOQUEIOATENDIMENTO() As String
            Get
                Return Me.bLOQUEIOATENDIMENTOField
            End Get
            Set
                Me.bLOQUEIOATENDIMENTOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CAUSAPROVAVEL() As String
            Get
                Return Me.cAUSAPROVAVELField
            End Get
            Set
                Me.cAUSAPROVAVELField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CODIGODEFEITO() As String
            Get
                Return Me.cODIGODEFEITOField
            End Get
            Set
                Me.cODIGODEFEITOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CODIGOGARANTIA() As String
            Get
                Return Me.cODIGOGARANTIAField
            End Get
            Set
                Me.cODIGOGARANTIAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CODIGOOCORRENCIA() As String
            Get
                Return Me.cODIGOOCORRENCIAField
            End Get
            Set
                Me.cODIGOOCORRENCIAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CODIGOSERVICO() As String
            Get
                Return Me.cODIGOSERVICOField
            End Get
            Set
                Me.cODIGOSERVICOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CODIGOSITUACAO() As String
            Get
                Return Me.cODIGOSITUACAOField
            End Get
            Set
                Me.cODIGOSITUACAOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CODIGOTECNICO() As String
            Get
                Return Me.cODIGOTECNICOField
            End Get
            Set
                Me.cODIGOTECNICOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property DATAFIM() As Date
            Get
                Return Me.dATAFIMField
            End Get
            Set
                Me.dATAFIMField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property DATAINICIO() As Date
            Get
                Return Me.dATAINICIOField
            End Get
            Set
                Me.dATAINICIOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DEFEITOCONSTATADO() As String
            Get
                Return Me.dEFEITOCONSTATADOField
            End Get
            Set
                Me.dEFEITOCONSTATADOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HORAFIM() As String
            Get
                Return Me.hORAFIMField
            End Get
            Set
                Me.hORAFIMField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HORAINICIO() As String
            Get
                Return Me.hORAINICIOField
            End Get
            Set
                Me.hORAINICIOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property INCLUIITEMOS() As String
            Get
                Return Me.iNCLUIITEMOSField
            End Get
            Set
                Me.iNCLUIITEMOSField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property ITENS() As ITEMATENDIMENTOSTRUCT()
            Get
                Return Me.iTENSField
            End Get
            Set
                Me.iTENSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MODOATENDIMENTO() As String
            Get
                Return Me.mODOATENDIMENTOField
            End Get
            Set
                Me.mODOATENDIMENTOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NUMEROATENDIMENTOOS() As String
            Get
                Return Me.nUMEROATENDIMENTOOSField
            End Get
            Set
                Me.nUMEROATENDIMENTOOSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NUMEROSERIEEQUIP() As String
            Get
                Return Me.nUMEROSERIEEQUIPField
            End Get
            Set
                Me.nUMEROSERIEEQUIPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ORDEMSERVICO() As String
            Get
                Return Me.oRDEMSERVICOField
            End Get
            Set
                Me.oRDEMSERVICOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SEQUENCIAATENDIMENTOOS() As String
            Get
                Return Me.sEQUENCIAATENDIMENTOOSField
            End Get
            Set
                Me.sEQUENCIAATENDIMENTOOSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SERVICOEXECUTADO() As String
            Get
                Return Me.sERVICOEXECUTADOField
            End Get
            Set
                Me.sERVICOEXECUTADOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TRASLADO() As String
            Get
                Return Me.tRASLADOField
            End Get
            Set
                Me.tRASLADOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VERSAOATUAL() As String
            Get
                Return Me.vERSAOATUALField
            End Get
            Set
                Me.vERSAOATUALField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VERSAOSOFTWARE() As String
            Get
                Return Me.vERSAOSOFTWAREField
            End Get
            Set
                Me.vERSAOSOFTWAREField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://10.230.2.44:91/")>  _
    Partial Public Class RETSTRUCT
        
        Private cHAVEField As String
        
        Private cODIGOField As Single
        
        Private mENSAGEMField As String
        
        Private sUCESSOField As Boolean
        
        '''<remarks/>
        Public Property CHAVE() As String
            Get
                Return Me.cHAVEField
            End Get
            Set
                Me.cHAVEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CODIGO() As Single
            Get
                Return Me.cODIGOField
            End Get
            Set
                Me.cODIGOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MENSAGEM() As String
            Get
                Return Me.mENSAGEMField
            End Get
            Set
                Me.mENSAGEMField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SUCESSO() As Boolean
            Get
                Return Me.sUCESSOField
            End Get
            Set
                Me.sUCESSOField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://10.230.2.44:91/")>  _
    Partial Public Class ITEMORDEMSERVICOSTRUCT
        
        Private cODIGOCLASSIFICACAOField As String
        
        Private cODIGOETAPAField As String
        
        Private cODIGOOCORRENCIAField As String
        
        Private cODIGOPRODUTOField As String
        
        Private cODIGOSITUACAOField As String
        
        Private cODIGOSTATUSField As String
        
        Private cOMENTARIOField As String
        
        Private d_E_L_E_T_Field As String
        
        Private nUMEROITEMField As String
        
        Private nUMEROSERIEField As String
        
        '''<remarks/>
        Public Property CODIGOCLASSIFICACAO() As String
            Get
                Return Me.cODIGOCLASSIFICACAOField
            End Get
            Set
                Me.cODIGOCLASSIFICACAOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CODIGOETAPA() As String
            Get
                Return Me.cODIGOETAPAField
            End Get
            Set
                Me.cODIGOETAPAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CODIGOOCORRENCIA() As String
            Get
                Return Me.cODIGOOCORRENCIAField
            End Get
            Set
                Me.cODIGOOCORRENCIAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CODIGOPRODUTO() As String
            Get
                Return Me.cODIGOPRODUTOField
            End Get
            Set
                Me.cODIGOPRODUTOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CODIGOSITUACAO() As String
            Get
                Return Me.cODIGOSITUACAOField
            End Get
            Set
                Me.cODIGOSITUACAOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CODIGOSTATUS() As String
            Get
                Return Me.cODIGOSTATUSField
            End Get
            Set
                Me.cODIGOSTATUSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property COMENTARIO() As String
            Get
                Return Me.cOMENTARIOField
            End Get
            Set
                Me.cOMENTARIOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property D_E_L_E_T_() As String
            Get
                Return Me.d_E_L_E_T_Field
            End Get
            Set
                Me.d_E_L_E_T_Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NUMEROITEM() As String
            Get
                Return Me.nUMEROITEMField
            End Get
            Set
                Me.nUMEROITEMField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NUMEROSERIE() As String
            Get
                Return Me.nUMEROSERIEField
            End Get
            Set
                Me.nUMEROSERIEField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://10.230.2.44:91/")>  _
    Partial Public Class ANEXOORDEMSERVICOSTRUCT
        
        Private d_E_L_E_T_Field As String
        
        Private dESCARQUIVOField As String
        
        Private nOMEARQUIVOField As String
        
        Private sEQARQUIVOField As String
        
        '''<remarks/>
        Public Property D_E_L_E_T_() As String
            Get
                Return Me.d_E_L_E_T_Field
            End Get
            Set
                Me.d_E_L_E_T_Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DESCARQUIVO() As String
            Get
                Return Me.dESCARQUIVOField
            End Get
            Set
                Me.dESCARQUIVOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NOMEARQUIVO() As String
            Get
                Return Me.nOMEARQUIVOField
            End Get
            Set
                Me.nOMEARQUIVOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SEQARQUIVO() As String
            Get
                Return Me.sEQARQUIVOField
            End Get
            Set
                Me.sEQARQUIVOField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://10.230.2.44:91/")>  _
    Partial Public Class FICHAORDEMSERVICOSTRUCT
        
        Private aNEXOSField() As ANEXOORDEMSERVICOSTRUCT
        
        Private cHAMADOOSField As String
        
        Private cNPJField As String
        
        Private cODIGOCLIENTEField As String
        
        Private cONTATOField As String
        
        Private iTENSField() As ITEMORDEMSERVICOSTRUCT
        
        Private nUMEROCHAMADOField As String
        
        Private nUMEROORDEMSERVICOField As String
        
        Private nUMEROOSPARCField As String
        
        Private tELEFONEField As String
        
        Private tIPOField As String
        
        Private tIPOORDEMSERVICOField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property ANEXOS() As ANEXOORDEMSERVICOSTRUCT()
            Get
                Return Me.aNEXOSField
            End Get
            Set
                Me.aNEXOSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CHAMADOOS() As String
            Get
                Return Me.cHAMADOOSField
            End Get
            Set
                Me.cHAMADOOSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CNPJ() As String
            Get
                Return Me.cNPJField
            End Get
            Set
                Me.cNPJField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CODIGOCLIENTE() As String
            Get
                Return Me.cODIGOCLIENTEField
            End Get
            Set
                Me.cODIGOCLIENTEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CONTATO() As String
            Get
                Return Me.cONTATOField
            End Get
            Set
                Me.cONTATOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property ITENS() As ITEMORDEMSERVICOSTRUCT()
            Get
                Return Me.iTENSField
            End Get
            Set
                Me.iTENSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NUMEROCHAMADO() As String
            Get
                Return Me.nUMEROCHAMADOField
            End Get
            Set
                Me.nUMEROCHAMADOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NUMEROORDEMSERVICO() As String
            Get
                Return Me.nUMEROORDEMSERVICOField
            End Get
            Set
                Me.nUMEROORDEMSERVICOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NUMEROOSPARC() As String
            Get
                Return Me.nUMEROOSPARCField
            End Get
            Set
                Me.nUMEROOSPARCField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TELEFONE() As String
            Get
                Return Me.tELEFONEField
            End Get
            Set
                Me.tELEFONEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TIPO() As String
            Get
                Return Me.tIPOField
            End Get
            Set
                Me.tIPOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TIPOORDEMSERVICO() As String
            Get
                Return Me.tIPOORDEMSERVICOField
            End Get
            Set
                Me.tIPOORDEMSERVICOField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub ALTERARCompletedEventHandler(ByVal sender As Object, ByVal e As ALTERARCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ALTERARCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RETSTRUCT
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RETSTRUCT)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub ATENDERCompletedEventHandler(ByVal sender As Object, ByVal e As ATENDERCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ATENDERCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RETSTRUCT
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RETSTRUCT)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub INCLUIRCompletedEventHandler(ByVal sender As Object, ByVal e As INCLUIRCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class INCLUIRCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RETSTRUCT
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RETSTRUCT)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub INCLUIROSCompletedEventHandler(ByVal sender As Object, ByVal e As INCLUIROSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class INCLUIROSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RETSTRUCT
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RETSTRUCT)
            End Get
        End Property
    End Class
End Namespace
