'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.230.2.42:91/WSORDEMSERVICO.apw?WSDL")>  _
        Public ReadOnly Property OrdemServico_wsmicrosigaP11_ordemservico_WSORDEMSERVICO() As String
            Get
                Return CType(Me("OrdemServico_wsmicrosigaP11_ordemservico_WSORDEMSERVICO"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.230.2.42:91/WSUSERAGILITY.apw?WSDL")>  _
        Public ReadOnly Property OrdemServico_wsmicrosigaP11_userutility_WSUSERAGILITY() As String
            Get
                Return CType(Me("OrdemServico_wsmicrosigaP11_userutility_WSUSERAGILITY"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.230.2.42:91/WSORDEMSERVICO.apw?WSDL")>  _
        Public ReadOnly Property OrdemServico_wsmicrosigaHomologacao_ordemservico_WSORDEMSERVICO() As String
            Get
                Return CType(Me("OrdemServico_wsmicrosigaHomologacao_ordemservico_WSORDEMSERVICO"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.230.2.42:91/WSUTILAGILITY.apw")>  _
        Public ReadOnly Property OrdemServico_wsmicrosigaHomologacao_utilagility_WSUTILAGILITY() As String
            Get
                Return CType(Me("OrdemServico_wsmicrosigaHomologacao_utilagility_WSUTILAGILITY"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.230.2.42:91/WSUSERAGILITY.apw?WSDL")>  _
        Public ReadOnly Property OrdemServico_wsmicrosigaHomologacao_userutility_WSUSERAGILITY() As String
            Get
                Return CType(Me("OrdemServico_wsmicrosigaHomologacao_userutility_WSUSERAGILITY"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.230.2.44:91/WSORDEMSERVICO.apw")>  _
        Public ReadOnly Property OrdemServico_wsmicrosiga_ordemservico_WSORDEMSERVICO() As String
            Get
                Return CType(Me("OrdemServico_wsmicrosiga_ordemservico_WSORDEMSERVICO"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.230.2.44:91/WSUSERAGILITY.apw")>  _
        Public ReadOnly Property OrdemServico_wsmicrosiga_useragility_WSUSERAGILITY() As String
            Get
                Return CType(Me("OrdemServico_wsmicrosiga_useragility_WSUSERAGILITY"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.230.2.44:91/WSUTILAGILITY.apw")>  _
        Public ReadOnly Property OrdemServico_wsmicrosiga_utilagility_WSUTILAGILITY() As String
            Get
                Return CType(Me("OrdemServico_wsmicrosiga_utilagility_WSUTILAGILITY"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.OrdemServico.My.MySettings
            Get
                Return Global.OrdemServico.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
