'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
'
Namespace wsmicrosiga.utilagility
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WSUTILAGILITYSOAP", [Namespace]:="http://10.230.2.42:91/")>  _
    Partial Public Class WSUTILAGILITY
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private WEBGETMVOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.OrdemServico.My.MySettings.Default.OrdemServico_wsmicrosiga_utilagility_WSUTILAGILITY
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event WEBGETMVCompleted As WEBGETMVCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.230.2.42:91/WEBGETMV", RequestNamespace:="http://10.230.2.42:91/", ResponseElementName:="WEBGETMVRESPONSE", ResponseNamespace:="http://10.230.2.42:91/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function WEBGETMV(ByVal TOKEN As TKNSTRUCT, ByVal NOMEPARAMETRO As String) As <System.Xml.Serialization.XmlElementAttribute("WEBGETMVRESULT")> String
            Dim results() As Object = Me.Invoke("WEBGETMV", New Object() {TOKEN, NOMEPARAMETRO})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub WEBGETMVAsync(ByVal TOKEN As TKNSTRUCT, ByVal NOMEPARAMETRO As String)
            Me.WEBGETMVAsync(TOKEN, NOMEPARAMETRO, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WEBGETMVAsync(ByVal TOKEN As TKNSTRUCT, ByVal NOMEPARAMETRO As String, ByVal userState As Object)
            If (Me.WEBGETMVOperationCompleted Is Nothing) Then
                Me.WEBGETMVOperationCompleted = AddressOf Me.OnWEBGETMVOperationCompleted
            End If
            Me.InvokeAsync("WEBGETMV", New Object() {TOKEN, NOMEPARAMETRO}, Me.WEBGETMVOperationCompleted, userState)
        End Sub
        
        Private Sub OnWEBGETMVOperationCompleted(ByVal arg As Object)
            If (Not (Me.WEBGETMVCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WEBGETMVCompleted(Me, New WEBGETMVCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://10.230.2.42:91/")>  _
    Partial Public Class TKNSTRUCT
        
        Private cONTEUDOField As String
        
        Private eMPRESAFILIALField As EMPFILIALSTRUCT
        
        Private mENSAGEMField As String
        
        Private mODULOField As String
        
        Private sENHAField As String
        
        Private sESSIONIDField As String
        
        Private sISTEMAField As String
        
        '''<remarks/>
        Public Property CONTEUDO() As String
            Get
                Return Me.cONTEUDOField
            End Get
            Set
                Me.cONTEUDOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EMPRESAFILIAL() As EMPFILIALSTRUCT
            Get
                Return Me.eMPRESAFILIALField
            End Get
            Set
                Me.eMPRESAFILIALField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MENSAGEM() As String
            Get
                Return Me.mENSAGEMField
            End Get
            Set
                Me.mENSAGEMField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MODULO() As String
            Get
                Return Me.mODULOField
            End Get
            Set
                Me.mODULOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SENHA() As String
            Get
                Return Me.sENHAField
            End Get
            Set
                Me.sENHAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SESSIONID() As String
            Get
                Return Me.sESSIONIDField
            End Get
            Set
                Me.sESSIONIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SISTEMA() As String
            Get
                Return Me.sISTEMAField
            End Get
            Set
                Me.sISTEMAField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://10.230.2.42:91/")>  _
    Partial Public Class EMPFILIALSTRUCT
        
        Private eMPRESAField As String
        
        Private fILIALField As String
        
        Private fILPARField As String
        
        '''<remarks/>
        Public Property EMPRESA() As String
            Get
                Return Me.eMPRESAField
            End Get
            Set
                Me.eMPRESAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FILIAL() As String
            Get
                Return Me.fILIALField
            End Get
            Set
                Me.fILIALField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FILPAR() As String
            Get
                Return Me.fILPARField
            End Get
            Set
                Me.fILPARField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub WEBGETMVCompletedEventHandler(ByVal sender As Object, ByVal e As WEBGETMVCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class WEBGETMVCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
